version: "3.8"
services: 
    web_app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        stdin_open: true # e nevoie pt react
        ports: 
            - "3000:80"
        volumes: 
            - /app_react/node_modules
            - .:/app_react
    test_app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /app_react/node_modules
            - .:/app_react
        command: ["npm", "run", "test"]